export default data = {
    MonitoringList: [
        {
            label: "Drinking Water",
            value: "Drinking Water",
        },
        {
            label: "Surface Water",
            value: "Surface Water",
        },
        {
            label: "Waste Water/Pollution",
            value: "Waste Water/Pollution",
        },
        {
            label: "Emergency",
            value: "Emergency",
        },
        {
            label: "Client",
            value: "Client",
        },
    ],
    WMZ: [{ label: 'Albert WMZ' }, { label: 'Kyoga WMZ' }, { label: 'Victoria WMZ' }, { label: 'Upper Nile WMZ' }, { label: 'Center' }],
    NetworkSW: [{ label: 'Factory' }, { label: 'Ambient' }],
    Whether: [{ label: 'Rainy', value: 'Rainy' }, { label: 'Cloudy', value: 'Cloudy' }, { label: 'Overcast', value: 'Overcast' }, { label: 'Windy', value: 'Windy' }, { label: 'Sunny', value: 'Sunny' }],
    Network: [
        {
            label: "Urban",
            value: "Urban",
        },
        {
            label: "Rural",
            value: "Rural",
        },
        {
            label: "Factory",
            value: "Factory",
        },
    ],
    SampleMatrix: [
        { label: 'Air' },
        { label: 'Water' },
        { label: 'Sediment' },
        { label: 'Biota' },
        { label: 'Other' }
    ],
    Question: [{ label: 'Yes' }, { label: 'No' }],
    waterType: [
        { label: 'Drinking Water' },
        { label: 'Surface Water' },
        { label: 'Waste Water/Pollution' }
    ],
    WastwaterType: [{ label: 'Industrial' }, { label: 'Municipal' }, { label: 'PMS' }],
    catchment: [
        { label: 'Victoria' },
        { label: 'Aswa' },
        { label: 'Albert' },
        { label: 'UppeNile' },
        { label: 'Kidepo' }
    ],

    WastwaterType:
        [
            { label: 'Industrial' },
            { label: 'Municipal' },
            { label: 'PMS' }
        ],

    SourceType: [
        { label: 'Bottle Water' },
        { label: 'Piped Water' },
        { label: 'Point Source' }
    ],
    SourceCategorySW: [
        { label: 'Lake' },
        { label: 'River' },
        { label: 'Stream' },
        { label: 'Swamp' }
    ],
    Unites: [
        { label: 'mS/cm' },
        { label: 'Meter' },
        { label: '(W/m2)' },
        { label: 'Fahrenheit (°F)' },
        { label: 'Celsius (°C)' },
        { label: 'Kelvin (K)' }
    ],
    EC: [{ label: 'mS/cm' }],
    PH: [{ label: 'Units' }],
    Turb: [{ label: 'Meter' }],
    PAR: [{ label: '(W/m2)' }],
    Temp: [
        { label: 'Fahrenheit (°F)' },
        { label: 'Celsius (°C)' },
        { label: 'Kelvin (K)' }],
    SourceCategory: {
        PipedWater: [
            { label: 'Kiosk' },
            { label: 'PSP' },
            { label: 'Standtap' }
        ],
        BottleWater: [
            { label: 'Bottle' },
            { label: 'Can' }
        ],
        PointSource:
            [
                { label: 'Deep well (B/H)' },
                { label: 'Open well' },
                { label: 'Shallow well (Hand Dug Well)' },
                { label: 'Protected Spring' },
                { label: 'Rainwater Harvest' },
                { label: 'Unprotected Spring' },
                { label: 'Valley dam' },
                { label: 'Other' },
            ]
    },
    regions: [
        { label: 'Region A' },
        { label: 'Region B' },
        { label: 'Region C' },
        { label: 'Region D' },
        { label: 'Region E' },
        { label: 'Region F' },
        { label: 'Region G' },
        { label: 'Region H' },
        { label: 'Region I' },
        { label: 'Region J' },
        { label: 'Region K' },
        { label: 'Region L' },
        { label: 'Region M' },
        { label: 'Region N' },
        { label: 'Region O' },
        { label: 'Region P' },
        { label: 'Region Q' },
        { label: 'Region R' },
        { label: 'Region S' },
        { label: 'Region T' },
    ],
    District: [
        { label: 'District X' },
        { label: 'District Y' },
        { label: 'District Z' },
        { label: 'District W' },
        { label: 'District V' },
        { label: 'District U' },
        { label: 'District T' },
        { label: 'District S' },
        { label: 'District R' },
        { label: 'District Q' },
        { label: 'District P' },
        { label: 'District O' },
        { label: 'District N' },
        { label: 'District M' },
        { label: 'District L' },
        { label: 'District K' },
        { label: 'District J' },
        { label: 'District I' },
        { label: 'District H' },
        { label: 'District G' },
    ],
    SubCounty: [
        { label: 'SubCounty One' },
        { label: 'SubCounty Two' },
        { label: 'SubCounty Three' },
        { label: 'SubCounty Four' },
        { label: 'SubCounty Five' },
        { label: 'SubCounty Six' },
        { label: 'SubCounty Seven' },
        { label: 'SubCounty Eight' },
        { label: 'SubCounty Nine' },
        { label: 'SubCounty Ten' },
        { label: 'SubCounty Eleven' },
        { label: 'SubCounty Twelve' },
        { label: 'SubCounty Thirteen' },
        { label: 'SubCounty Fourteen' },
        { label: 'SubCounty Fifteen' },
        { label: 'SubCounty Sixteen' },
        { label: 'SubCounty Seventeen' },
        { label: 'SubCounty Eighteen' },
        { label: 'SubCounty Nineteen' },
        { label: 'SubCounty Twenty' },
    ],
    Parish: [
        { label: 'Parish A' },
        { label: 'Parish B' },
        { label: 'Parish C' },
        { label: 'Parish D' },
        { label: 'Parish E' },
        { label: 'Parish F' },
        { label: 'Parish G' },
        { label: 'Parish H' },
        { label: 'Parish I' },
        { label: 'Parish J' },
        { label: 'Parish K' },
        { label: 'Parish L' },
        { label: 'Parish M' },
        { label: 'Parish N' },
        { label: 'Parish O' },
        { label: 'Parish P' },
        { label: 'Parish Q' },
        { label: 'Parish R' },
        { label: 'Parish S' },
        { label: 'Parish T' },
    ],
    County: [
        { label: 'County Alpha' },
        { label: 'County Beta' },
        { label: 'County Gamma' },
        { label: 'County Delta' },
        { label: 'County Epsilon' },
        { label: 'County Zeta' },
        { label: 'County Eta' },
        { label: 'County Theta' },
        { label: 'County Iota' },
        { label: 'County Kappa' },
        { label: 'County Lambda' },
        { label: 'County Mu' },
        { label: 'County Nu' },
        { label: 'County Xi' },
        { label: 'County Omicron' },
        { label: 'County Pi' },
        { label: 'County Rho' },
        { label: 'County Sigma' },
        { label: 'County Tau' },
        { label: 'County Upsilon' },
    ],
}